# Generated by Django 6.0 on 2026-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cart_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
migrations.CreateModel(
    name='CartItem',
    fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('quantity', models.PositiveIntegerField(default=1)),
        ('product', models.ForeignKey(on_delete=models.CASCADE, to='store.products')),
        ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='cart_items', to='auth.user')),
    ],
    options={
        'unique_together': {('user', 'product')},
    },
)
