# Generated by Django 6.0 on 2026-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_create_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, help_text="qty"),
        ),
    ]
