# Generated by Django 6.0 on 2026-01-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_savedaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedaddress",
            name="city",
        ),
        migrations.RemoveField(
            model_name="savedaddress",
            name="state",
        ),
    ]
