# Generated by Django 6.0 on 2026-02-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_savedaddress_city_remove_savedaddress_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="reviews",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
