# Generated by Django 6.0 on 2026-02-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_products_rating_products_reviews"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WishlistItem",
        ),
    ]
